### ISSUE TITLE
This library doesn't work in IE6

### ISSUE THREAD

**Issue by agentfitz** [edull24/ScrollWatch#11]
Most of the time I wouldn't make a big deal of this, but, BUT, I have a client who is dead set, read my lips DEAD SET on having infinite scrolling (with parallax effects) in IE6, and on his Blackberry two-way pager.

Listen, I understand this request might sound a bit ridiculous, but considering ScrollWatch is more of a "lower-level" library (and not really a UI component), I think this is very achievable and I would really appreciate you rolling in official support for these devices.

Thanks, cordially awaiting your timely reply.

Bernardo Fitzkerlad

**Comment by edull24** [comment]
Works for me ;)
