### ISSUE TITLE
Allow passing of DOM element to options.container

### ISSUE THREAD

**Issue by joshgillies** [edull24/ScrollWatch#12]
Currently if you want to use a container other than the default `window.document.documentElement`, you can only do so by passing a selector. https://github.com/edull24/ScrollWatch/blob/master/src/ScrollWatch.js#L174

It would be useful if in addition to passing a selector, `options.container` also accepted a DOM node.

eg.
```js
var swInstance = new ScrollWatch({
  container: document.getElementById('sw-container')
});
```

**Comment by edull24** [comment]
@joshgillies Thanks for the comment. Can you elaborate on why you think it would be useful? Are there any direct benefits to passing in a node vs a selector, or do you see this more as a convenience?

**Comment by joshgillies** [comment]
Hey @edull24 my comment is somewhere between convenience and expected behaviour. A few other utilities like ScrollWatch we're using in our project accept either a valid CSS Selector or DOM Node as input.

However for a particular use case, we have a list of data driven components which are mounted to the DOM at an irregular interval, while we could use a single SW instance and call `sw.refresh()` with every new element inserted into the DOM, to me it feels a little cleaner to simply have each component manage it's own SW instance, creating it on demand and destroying it once no longer required.

**Comment by edull24** [comment]
@joshgillies Thanks for the feedback! I'll look into adding this as soon as I can.

**Comment by joshgillies** [comment]
@edull24 nice! Let me know if you need a hand at all 👍
